# permissions for end users to edit grayreleases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grayrelease-editor-role
rules:
- apiGroups:
  - release.icks.inspur.com
  resources:
  - grayreleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - release.icks.inspur.com
  resources:
  - grayreleases/status
  verbs:
  - get
